# Generated by Django 5.2.17 on 2026-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=30, unique=True, verbose_name='Roll Number / Enrollment ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('course', models.CharField(max_length=100, verbose_name='Course / Branch')),
                ('academic_year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('PG - 1st Year', 'PG - 1st Year'), ('PG - 2nd Year', 'PG - 2nd Year')], default='1st Year', max_length=50, verbose_name='Academic Year')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('abc_id', models.CharField(max_length=50, verbose_name='ABC ID (Academic Bank of Credits)')),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Fees (₹)')),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fees Paid (₹)')),
                ('fee_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], default='Pending', max_length=20, verbose_name='Fee Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
